### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by barrett092** [hypn0s/AJPy#12]
Getting this error anytime I try to run this tool.

**Comment by rkgyellowjacket** [comment]
^^ same issue on centos and macos

**Comment by hypn0s** [comment]
Hi guys,

Thank you for reporting issues but I'm gonna need more details such as:
- are you using AJPy as a library or are you using tomcat.py?
- tomcat version?
- command line used?
- full stack trace?
- python2 or python3 ?

Thank you in advance for the details, it will help me to understand what's wrong.

**Comment by giacomo** [comment]
@hypn0s 

Using python 2.7.13

```
Traceback (most recent call last):
  File "tomcat.py", line 363, in <module>
    print(bf.get_version())
  File "tomcat.py", line 213, in get_version
    hdrs, data = self.get_error_page()
  File "tomcat.py", line 210, in get_error_page
    return self.perform_request("/blablablablabla")
  File "tomcat.py", line 153, in perform_request
    responses = self.forward_request.send_and_receive(self.socket, self.stream)
  File "C:\Downloads\AJPy-master\AJPy-master\ajpy\ajp.py", line 274, in send_and_receive
    r = AjpResponse.receive(stream)
  File "C:\Downloads\AJPy-master\AJPy-master\ajpy\ajp.py", line 380, in receive
    r.parse(stream)
  File "C:\Downloads\AJPy-master\AJPy-master\ajpy\ajp.py", line 348, in parse
    raise NotImplementedError
NotImplementedError
```

**Comment by hypn0s** [comment]
You did not respond with all the details I need to debug your issue. I'm closing it as it's been a while now.
